// <auto-generated />
using Livraria.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Livraria.WebAPI.Migrations
{
    [DbContext(typeof(LivrariaContext))]
    [Migration("20211015094107_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Livraria.WebAPI.Models.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LivroId");

                    b.ToTable("Alugueis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            LivroId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 4,
                            LivroId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 1,
                            LivroId = 3
                        });
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CidadeCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidadeCliente = "Fortaleza",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 27",
                            NomeCliente = "Marta"
                        },
                        new
                        {
                            Id = 2,
                            CidadeCliente = "Bahia",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 21",
                            NomeCliente = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            CidadeCliente = "SaoPaulo",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 22",
                            NomeCliente = "Laura"
                        },
                        new
                        {
                            Id = 4,
                            CidadeCliente = "Juazeiro",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 23",
                            NomeCliente = "Luiza"
                        },
                        new
                        {
                            Id = 5,
                            CidadeCliente = "Fortim",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 24",
                            NomeCliente = "Lucas"
                        },
                        new
                        {
                            Id = 6,
                            CidadeCliente = "Aracati",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 25",
                            NomeCliente = "Pedro"
                        },
                        new
                        {
                            Id = 7,
                            CidadeCliente = "Quixaba",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 26",
                            NomeCliente = "Paulo"
                        });
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Editora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CidadeEditora")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEditora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Editoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidadeEditora = "Fortaleza",
                            NameEditora = "Viva"
                        },
                        new
                        {
                            Id = 2,
                            CidadeEditora = "Fortaleza",
                            NameEditora = "Tim"
                        },
                        new
                        {
                            Id = 3,
                            CidadeEditora = "Fortaleza",
                            NameEditora = "Dominas"
                        },
                        new
                        {
                            Id = 4,
                            CidadeEditora = "Fortaleza",
                            NameEditora = "Cacau"
                        },
                        new
                        {
                            Id = 5,
                            CidadeEditora = "Fortaleza",
                            NameEditora = "Prog"
                        });
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorLivro")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditoraID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LancamentoLivro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeLivro")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EditoraID");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorLivro = "João Sthepfan",
                            EditoraID = 2,
                            LancamentoLivro = "04/2005",
                            NomeLivro = "Harry",
                            Quantidade = 100
                        },
                        new
                        {
                            Id = 2,
                            AutorLivro = "Jo Sthepf",
                            EditoraID = 2,
                            LancamentoLivro = "05/2010",
                            NomeLivro = "Potter",
                            Quantidade = 80
                        },
                        new
                        {
                            Id = 3,
                            AutorLivro = "Marcos fan",
                            EditoraID = 2,
                            LancamentoLivro = "06/2003",
                            NomeLivro = "RosiVelw",
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 4,
                            AutorLivro = "JoJo epn",
                            EditoraID = 2,
                            LancamentoLivro = "07/2005",
                            NomeLivro = "Biblia",
                            Quantidade = 70
                        },
                        new
                        {
                            Id = 5,
                            AutorLivro = "Henrique Show",
                            EditoraID = 2,
                            LancamentoLivro = "08/2008",
                            NomeLivro = "Thomas",
                            Quantidade = 60
                        });
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Aluguel", b =>
                {
                    b.HasOne("Livraria.WebAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livraria.WebAPI.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Livro", b =>
                {
                    b.HasOne("Livraria.WebAPI.Models.Editora", "Editora")
                        .WithMany()
                        .HasForeignKey("EditoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
