// <auto-generated />
using Livraria.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Livraria.WebAPI.Migrations
{
    [DbContext(typeof(LivrariaContext))]
    partial class LivrariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Livraria.WebAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CidadeCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoCliente")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidadeCliente = "Fortaleza",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 27",
                            IdCliente = 0,
                            NomeCliente = "Marta"
                        },
                        new
                        {
                            Id = 2,
                            CidadeCliente = "Bahia",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 21",
                            IdCliente = 0,
                            NomeCliente = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            CidadeCliente = "SaoPaulo",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 22",
                            IdCliente = 0,
                            NomeCliente = "Laura"
                        },
                        new
                        {
                            Id = 4,
                            CidadeCliente = "Juazeiro",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 23",
                            IdCliente = 0,
                            NomeCliente = "Luiza"
                        },
                        new
                        {
                            Id = 5,
                            CidadeCliente = "Fortim",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 24",
                            IdCliente = 0,
                            NomeCliente = "Lucas"
                        },
                        new
                        {
                            Id = 6,
                            CidadeCliente = "Aracati",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 25",
                            IdCliente = 0,
                            NomeCliente = "Pedro"
                        },
                        new
                        {
                            Id = 7,
                            CidadeCliente = "Quixaba",
                            EmailCliente = "prohenriquelima@gmail.com",
                            EnderecoCliente = "Rua 26",
                            IdCliente = 0,
                            NomeCliente = "Paulo"
                        });
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Editora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CidadeEditora")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEditora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEditora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Editoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidadeEditora = "Fortaleza",
                            IdEditora = 0,
                            NameEditora = "Viva"
                        },
                        new
                        {
                            Id = 2,
                            CidadeEditora = "Fortaleza",
                            IdEditora = 0,
                            NameEditora = "Tim"
                        },
                        new
                        {
                            Id = 3,
                            CidadeEditora = "Fortaleza",
                            IdEditora = 0,
                            NameEditora = "Dominas"
                        },
                        new
                        {
                            Id = 4,
                            CidadeEditora = "Fortaleza",
                            IdEditora = 0,
                            NameEditora = "Cacau"
                        },
                        new
                        {
                            Id = 5,
                            CidadeEditora = "Fortaleza",
                            IdEditora = 0,
                            NameEditora = "Prog"
                        });
                });

            modelBuilder.Entity("Livraria.WebAPI.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEditora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeLivro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEditora = 0,
                            NomeLivro = "Harry"
                        },
                        new
                        {
                            Id = 2,
                            IdEditora = 0,
                            NomeLivro = "Potter"
                        },
                        new
                        {
                            Id = 3,
                            IdEditora = 0,
                            NomeLivro = "RosiVelw"
                        },
                        new
                        {
                            Id = 4,
                            IdEditora = 0,
                            NomeLivro = "Biblia"
                        },
                        new
                        {
                            Id = 5,
                            IdEditora = 0,
                            NomeLivro = "Thomas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
